import type { ThemeDef } from './types/index.ts'

export const themes: ThemeDef[] = [
  {
    id: 'midnight',
    label: 'Midnight',
    scheme: 'dark',
    vars: {
      bgBase: '#0f1117',
      bgSurface: '#1a1d27',
      bgSurface2: '#22263a',
      bgBorder: '#2d3142',
      accent: '#6366f1',
      accentFg: '#ffffff',
      fgPrimary: '#ffffff',
      fgSecondary: '#94a3b8',
      fgMuted: '#64748b',
      userBubble: '#6366f1',
      userBubbleFg: '#ffffff',
    },
  },
  {
    id: 'ivory',
    label: 'Ivory',
    scheme: 'light',
    vars: {
      bgBase: '#ffffff',
      bgSurface: '#f1f5f9',
      bgSurface2: '#e2e8f0',
      bgBorder: '#cbd5e1',
      accent: '#4338ca',
      accentFg: '#ffffff',
      fgPrimary: '#0f172a',
      fgSecondary: '#334155',
      fgMuted: '#64748b',
      userBubble: '#4338ca',
      userBubbleFg: '#ffffff',
    },
  },
  {
    id: 'sunrise',
    label: 'Sunrise',
    scheme: 'light',
    vars: {
      bgBase: '#ffffff',
      bgSurface: '#fff7ed',
      bgSurface2: '#ffedd5',
      bgBorder: '#fed7aa',
      accent: '#f97316',
      accentFg: '#ffffff',
      fgPrimary: '#1c0a00',
      fgSecondary: '#431407',
      fgMuted: '#9a3412',
      userBubble: '#f97316',
      userBubbleFg: '#ffffff',
    },
  },
  {
    id: 'cosmos',
    label: 'Cosmos',
    scheme: 'dark',
    vars: {
      bgBase: '#0d0a1a',
      bgSurface: '#15102b',
      bgSurface2: '#1e1840',
      bgBorder: '#2e2555',
      accent: '#a855f7',
      accentFg: '#ffffff',
      fgPrimary: '#f3e8ff',
      fgSecondary: '#c4b5fd',
      fgMuted: '#7c3aed',
      userBubble: '#a855f7',
      userBubbleFg: '#ffffff',
    },
  },
  {
    id: 'forest',
    label: 'Forest',
    scheme: 'dark',
    vars: {
      bgBase: '#0a1410',
      bgSurface: '#111f18',
      bgSurface2: '#162b1f',
      bgBorder: '#1e3a2a',
      accent: '#22c55e',
      accentFg: '#ffffff',
      fgPrimary: '#dcfce7',
      fgSecondary: '#86efac',
      fgMuted: '#4ade80',
      userBubble: '#16a34a',
      userBubbleFg: '#ffffff',
    },
  },
  {
    id: 'ocean',
    label: 'Ocean',
    scheme: 'dark',
    vars: {
      bgBase: '#060f1a',
      bgSurface: '#0c1b2e',
      bgSurface2: '#112440',
      bgBorder: '#163354',
      accent: '#06b6d4',
      accentFg: '#ffffff',
      fgPrimary: '#e0f7fa',
      fgSecondary: '#67e8f9',
      fgMuted: '#0891b2',
      userBubble: '#0891b2',
      userBubbleFg: '#ffffff',
    },
  },
  {
    id: 'cherry',
    label: 'Cherry',
    scheme: 'dark',
    vars: {
      bgBase: '#120608',
      bgSurface: '#1e0c10',
      bgSurface2: '#2a1016',
      bgBorder: '#3d1520',
      accent: '#ef4444',
      accentFg: '#ffffff',
      fgPrimary: '#ffe4e6',
      fgSecondary: '#fca5a5',
      fgMuted: '#f87171',
      userBubble: '#dc2626',
      userBubbleFg: '#ffffff',
    },
  },
  {
    id: 'navy',
    label: 'Navy',
    scheme: 'dark',
    vars: {
      bgBase: '#080f1e',
      bgSurface: '#0f1a33',
      bgSurface2: '#162348',
      bgBorder: '#1e3060',
      accent: '#3b82f6',
      accentFg: '#ffffff',
      fgPrimary: '#dbeafe',
      fgSecondary: '#93c5fd',
      fgMuted: '#60a5fa',
      userBubble: '#2563eb',
      userBubbleFg: '#ffffff',
    },
  },
  {
    id: 'lavender',
    label: 'Lavender',
    scheme: 'light',
    vars: {
      bgBase: '#faf5ff',
      bgSurface: '#f3e8ff',
      bgSurface2: '#e9d5ff',
      bgBorder: '#d8b4fe',
      accent: '#8b5cf6',
      accentFg: '#ffffff',
      fgPrimary: '#2e1065',
      fgSecondary: '#4c1d95',
      fgMuted: '#7c3aed',
      userBubble: '#7c3aed',
      userBubbleFg: '#ffffff',
    },
  },
  {
    id: 'amber',
    label: 'Amber',
    scheme: 'dark',
    vars: {
      bgBase: '#0f0a00',
      bgSurface: '#1c1400',
      bgSurface2: '#2a1d00',
      bgBorder: '#3d2c00',
      accent: '#f59e0b',
      accentFg: '#000000',
      fgPrimary: '#fef3c7',
      fgSecondary: '#fcd34d',
      fgMuted: '#d97706',
      userBubble: '#d97706',
      userBubbleFg: '#000000',
    },
  },
]

export const defaultThemeId = 'midnight'

export function getTheme(id: string): ThemeDef {
  return themes.find((t) => t.id === id) ?? themes[0]!
}
